In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,classification_report
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
df=pd.read_csv("titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
df=df[['Survived','Pclass','Age','SibSp','Parch']]
df

     Survived  Pclass   Age  SibSp  Parch
0           0       3  22.0      1      0
1           1       1  38.0      1      0
2           1       3  26.0      0      0
3           1       1  35.0      1      0
4           0       3  35.0      0      0
..        ...     ...   ...    ...    ...
886         0       2  27.0      0      0
887         1       1  19.0      0      0
888         0       3   NaN      1      2
889         1       1  26.0      0      0
890         0       3  32.0      0      0

[891 rows x 5 columns]

In [8]:
df.dropna(inplace=True)
df

     Survived  Pclass   Age  SibSp  Parch
0           0       3  22.0      1      0
1           1       1  38.0      1      0
2           1       3  26.0      0      0
3           1       1  35.0      1      0
4           0       3  35.0      0      0
..        ...     ...   ...    ...    ...
885         0       3  39.0      0      5
886         0       2  27.0      0      0
887         1       1  19.0      0      0
889         1       1  26.0      0      0
890         0       3  32.0      0      0

[714 rows x 5 columns]

In [9]:
X=df[['Pclass','Age','SibSp','Parch']]
X

     Pclass   Age  SibSp  Parch
0         3  22.0      1      0
1         1  38.0      1      0
2         3  26.0      0      0
3         1  35.0      1      0
4         3  35.0      0      0
..      ...   ...    ...    ...
885       3  39.0      0      5
886       2  27.0      0      0
887       1  19.0      0      0
889       1  26.0      0      0
890       3  32.0      0      0

[714 rows x 4 columns]

In [10]:
y=df['Survived']
y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [12]:
scalar=StandardScaler()
X_scaled=scalar.fit_transform(X)
X_scaled

array([[ 0.91123237, -0.53037664,  0.52457013, -0.50589515],
       [-1.47636364,  0.57183099,  0.52457013, -0.50589515],
       [ 0.91123237, -0.25482473, -0.55170307, -0.50589515],
       ...,
       [-1.47636364, -0.73704057, -0.55170307, -0.50589515],
       [-1.47636364, -0.25482473, -0.55170307, -0.50589515],
       [ 0.91123237,  0.15850313, -0.55170307, -0.50589515]])

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.2,random_state=42)

In [15]:
X_train

array([[ 0.91123237,  0.08961515,  0.52457013,  0.66686178],
       [ 0.91123237, -0.25482473,  0.52457013, -0.50589515],
       [ 0.91123237,  0.02072718,  0.52457013, -0.50589515],
       ...,
       [-1.47636364,  0.77849493, -0.55170307, -0.50589515],
       [ 0.91123237,  0.22739111,  0.52457013,  0.66686178],
       [ 0.91123237,  0.22739111, -0.55170307, -0.50589515]])

In [16]:
X_test

array([[-0.28256564,  0.8473829 , -0.55170307, -0.50589515],
       [-0.28256564, -1.83924821,  0.52457013,  0.66686178],
       [-0.28256564, -0.0481608 ,  0.52457013, -0.50589515],
       [-1.47636364, -0.39260069, -0.55170307, -0.50589515],
       [ 0.91123237,  0.91627088, -0.55170307, -0.50589515],
       [-0.28256564, -1.49480832,  0.52457013,  0.66686178],
       [ 0.91123237,  0.22739111,  2.67711654, -0.50589515],
       [-0.28256564,  1.67403863,  0.52457013,  3.01237564],
       [ 0.91123237, -0.11704878, -0.55170307, -0.50589515],
       [ 0.91123237, -0.46148866, -0.55170307, -0.50589515],
       [-1.47636364, -0.87481653,  0.52457013, -0.50589515],
       [-0.28256564,  0.19294712, -0.55170307, -0.50589515],
       [-1.47636364,  0.08961515,  0.52457013, -0.50589515],
       [ 0.91123237,  0.57183099, -0.55170307, -0.50589515],
       [-1.47636364,  0.36516706, -0.55170307, -0.50589515],
       [-0.28256564, -0.46148866,  1.60084334,  0.66686178],
       [ 0.91123237, -0.42704467, -0.55170307, -0.50589515],
       [-1.47636364, -0.9437045 , -0.55170307,  0.66686178],
       [-0.28256564, -0.18593675, -0.55170307, -0.50589515],
       [-1.47636364,  1.67403863,  0.52457013, -0.50589515],
       [ 0.91123237, -0.9437045 ,  4.82966295,  1.83961871],
       [-0.28256564,  1.39848672, -0.55170307,  0.66686178],
       [ 0.91123237, -1.42592034,  0.52457013,  0.66686178],
       [-1.47636364,  0.36516706, -0.55170307, -0.50589515],
       [ 0.91123237, -0.53037664, -0.55170307, -0.50589515],
       [ 0.91123237, -0.87481653, -0.55170307, -0.50589515],
       [ 0.91123237, -0.9437045 , -0.55170307, -0.50589515],
       [ 0.91123237, -0.25482473,  0.52457013,  1.83961871],
       [ 0.91123237, -1.04703647,  0.52457013, -0.50589515],
       [ 0.91123237,  0.57183099, -0.55170307, -0.50589515],
       [ 0.91123237, -0.59926462,  0.52457013, -0.50589515],
       [ 0.91123237, -1.42592034,  1.60084334,  1.83961871],
       [-1.47636364,  0.43405504, -0.55170307, -0.50589515],
       [ 0.91123237,  0.36516706, -0.55170307, -0.50589515],
       [ 0.91123237,  0.50294302,  1.60084334, -0.50589515],
       [ 0.91123237,  0.43405504,  0.52457013, -0.50589515],
       [-0.28256564,  0.29627909,  0.52457013, -0.50589515],
       [-1.47636364,  1.81181458, -0.55170307, -0.50589515],
       [-1.47636364,  2.15625447, -0.55170307, -0.50589515],
       [ 0.91123237,  1.4673747 , -0.55170307, -0.50589515],
       [ 0.91123237, -1.42592034, -0.55170307,  1.83961871],
       [ 0.91123237, -0.6681526 , -0.55170307, -0.50589515],
       [-1.47636364,  0.43405504,  0.52457013,  1.83961871],
       [-0.28256564,  1.67403863, -0.55170307, -0.50589515],
       [-1.47636364,  1.53626267,  0.52457013,  0.66686178],
       [-0.28256564, -0.0481608 , -0.55170307, -0.50589515],
       [-0.28256564,  0.29627909,  0.52457013,  0.66686178],
       [ 0.91123237, -0.59926462,  1.60084334,  1.83961871],
       [-1.47636364,  0.70960695, -0.55170307, -0.50589515],
       [-1.47636364,  1.26071077,  0.52457013, -0.50589515],
       [-1.47636364,  0.50294302,  0.52457013, -0.50589515],
       [-0.28256564, -0.39260069, -0.55170307, -0.50589515],
       [-1.47636364, -0.18593675,  0.52457013, -0.50589515],
       [ 0.91123237, -0.11704878, -0.55170307, -0.50589515],
       [ 0.91123237, -0.32371271, -0.55170307, -0.50589515],
       [-0.28256564,  1.88070256, -0.55170307, -0.50589515],
       [-1.47636364, -0.11704878, -0.55170307, -0.50589515],
       [ 0.91123237, -1.83924821,  3.75338974,  1.83961871],
       [ 0.91123237, -0.25482473,  0.52457013, -0.50589515],
       [-0.28256564,  2.22514245, -0.55170307, -0.50589515],
       [-1.47636364,  1.94959054, -0.55170307, -0.50589515],
       [ 0.91123237, -0.32371271, -0.55170307, -0.50589515],
       [-0.28256564,  1.05404683,  0.52457013,  0.66686178],
       [ 0.91123237, -0.87481653, -0.55170307, -0.50589515],
       [-0.28256564, -0.73704057, -0.55170307, -0.50589515],
       [-1.47636364,  1.19182279, -0.55170307, -0.50589515],
       [ 0.91123237, -1.63258428, -0.55170307,  0.66686178],
       [-1.47636364, -0.53037664, -0.55170307,  0.66686178],
       [ 0.91123237,  0.08961515, -0.55170307, -0.50589515],
       [-1.47636364,  0.22739111, -0.55170307, -0.50589515],
       [ 0.91123237, -0.87481653, -0.55170307, -0.50589515],
       [-1.47636364,  2.22514245, -0.55170307, -0.50589515],
       [ 0.91123237, -0.9437045 ,  0.52457013,  0.66686178],
       [ 0.91123237, -0.6681526 , -0.55170307, -0.50589515],
       [ 0.91123237,  1.05404683, -0.55170307, -0.50589515],
       [ 0.91123237, -0.6681526 ,  0.52457013, -0.50589515],
       [-0.28256564, -0.73704057, -0.55170307, -0.50589515],
       [ 0.91123237, -0.80592855, -0.55170307, -0.50589515],
       [ 0.91123237,  0.05517117, -0.55170307, -0.50589515],
       [-1.47636364, -1.28814439,  0.52457013,  1.83961871],
       [ 0.91123237, -1.28814439,  3.75338974,  1.83961871],
       [-1.47636364,  0.08961515,  0.52457013, -0.50589515],
       [ 0.91123237,  0.70960695,  0.52457013, -0.50589515],
       [ 0.91123237, -0.73704057, -0.55170307, -0.50589515],
       [ 0.91123237, -0.32371271, -0.55170307, -0.50589515],
       [ 0.91123237, -0.6681526 , -0.55170307, -0.50589515],
       [ 0.91123237, -1.42592034,  3.75338974,  1.83961871],
       [ 0.91123237,  0.74405094, -0.55170307, -0.50589515],
       [ 0.91123237, -0.73704057, -0.55170307, -0.50589515],
       [-0.28256564, -0.59926462, -0.55170307, -0.50589515],
       [-1.47636364,  1.05404683, -0.55170307, -0.50589515],
       [-1.47636364,  0.57183099, -0.55170307, -0.50589515],
       [-0.28256564,  1.39848672, -0.55170307, -0.50589515],
       [ 0.91123237, -0.0481608 ,  0.52457013, -0.50589515],
       [-0.28256564,  0.29627909, -0.55170307,  0.66686178],
       [ 0.91123237, -0.25482473, -0.55170307, -0.50589515],
       [-1.47636364, -0.39260069, -0.55170307, -0.50589515],
       [-1.47636364, -0.0481608 , -0.55170307, -0.50589515],
       [-0.28256564,  0.02072718, -0.55170307, -0.50589515],
       [ 0.91123237,  0.64071897, -0.55170307,  5.3578895 ],
       [-0.28256564, -0.11704878, -0.55170307, -0.50589515],
       [-0.28256564, -0.73704057, -0.55170307, -0.50589515],
       [ 0.91123237,  0.02072718, -0.55170307, -0.50589515],
       [ 0.91123237, -1.83924821,  2.67711654,  0.66686178],
       [-0.28256564, -1.77036023,  1.60084334,  0.66686178],
       [-0.28256564,  0.29627909,  0.52457013, -0.50589515],
       [ 0.91123237, -0.6681526 , -0.55170307, -0.50589515],
       [-1.47636364,  0.43405504,  0.52457013, -0.50589515],
       [ 0.91123237,  0.98515886, -0.55170307, -0.50589515],
       [-0.28256564,  0.70960695,  0.52457013,  0.66686178],
       [ 0.91123237, -0.11704878, -0.55170307, -0.50589515],
       [ 0.91123237, -0.59926462, -0.55170307, -0.50589515],
       [ 0.91123237, -1.42592034,  3.75338974,  1.83961871],
       [-1.47636364,  1.53626267, -0.55170307, -0.50589515],
       [ 0.91123237, -0.87481653, -0.55170307, -0.50589515],
       [ 0.91123237,  0.02072718, -0.55170307, -0.50589515],
       [ 0.91123237,  0.15850313,  0.52457013, -0.50589515],
       [ 0.91123237, -1.08148046,  0.52457013, -0.50589515],
       [ 0.91123237, -0.0481608 , -0.55170307, -0.50589515],
       [ 0.91123237,  0.91627088, -0.55170307, -0.50589515],
       [-1.47636364, -0.87481653,  0.52457013, -0.50589515],
       [ 0.91123237, -1.28814439,  4.82966295,  1.83961871],
       [ 0.91123237, -0.32371271,  0.52457013, -0.50589515],
       [ 0.91123237, -0.6681526 , -0.55170307, -0.50589515],
       [-1.47636364, -0.32371271,  0.52457013,  1.83961871],
       [ 0.91123237, -0.25482473, -0.55170307, -0.50589515],
       [ 0.91123237, -0.59926462, -0.55170307, -0.50589515],
       [-0.28256564, -0.87481653, -0.55170307, -0.50589515],
       [ 0.91123237, -0.0481608 , -0.55170307, -0.50589515],
       [-1.47636364,  0.98515886, -0.55170307, -0.50589515],
       [ 0.91123237, -0.32371271,  0.52457013, -0.50589515],
       [ 0.91123237, -0.11704878,  1.60084334, -0.50589515],
       [ 0.91123237, -0.25482473, -0.55170307, -0.50589515],
       [-0.28256564,  0.29627909, -0.55170307, -0.50589515],
       [ 0.91123237, -1.90813618,  2.67711654,  0.66686178],
       [ 0.91123237, -0.53037664, -0.55170307, -0.50589515],
       [ 0.91123237,  0.22739111, -0.55170307, -0.50589515],
       [-1.47636364,  0.50294302, -0.55170307,  0.66686178],
       [ 0.91123237, -1.35703237,  2.67711654,  1.83961871],
       [ 0.91123237, -1.97702416,  3.75338974,  0.66686178],
       [ 0.91123237,  0.36516706, -0.55170307, -0.50589515],
       [-0.28256564, -0.59926462, -0.55170307, -0.50589515],
       [-1.47636364, -0.73704057, -0.55170307,  1.83961871]])

In [17]:
y_train

328    1
73     0
253    0
719    0
666    0
      ..
92     0
134    0
337    1
548    0
130    0
Name: Survived, Length: 571, dtype: int64

In [18]:
y_test

149    0
407    1
53     1
369    1
818    0
      ..
819    0
164    0
363    0
56     1
136    1
Name: Survived, Length: 143, dtype: int64

In [19]:
log_model=LogisticRegression()

In [20]:
log_model.fit(X_train,y_train)

LogisticRegression()

In [21]:
y_pred=log_model.predict(X_test)

In [22]:
accuracy=accuracy_score(y_test,y_pred)

In [25]:
print(f"Accuracy: {accuracy*100:2f}%")

Accuracy: 69.230769%

In [26]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      0.84      0.77        87
           1       0.65      0.46      0.54        56

    accuracy                           0.69       143
   macro avg       0.68      0.65      0.66       143
weighted avg       0.69      0.69      0.68       143

In [3]:
import seaborn as sns
iris=sns.load_dataset('iris')
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]