In [34]:
from Demos.win32cred_demo import pwd

mystring='hello'

In [35]:
mystring.capitalize()

'Hello'

In [36]:
mystring.isdigit()

False

In [37]:
import pandas as pd

In [38]:
names=pd.Series(['andrew','bobo','claire','david','4'])
names

0    andrew
1      bobo
2    claire
3     david
4         4
dtype: object

In [39]:
names.str.capitalize()

0    Andrew
1      Bobo
2    Claire
3     David
4         4
dtype: object

In [40]:
names.str.isdigit()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [41]:
tech_finance=['GOOG,APPL,AMZN','JPM,BAC,GS']

In [42]:
len(tech_finance)

2

In [43]:
tickets=pd.Series(tech_finance)
tickets

0    GOOG,APPL,AMZN
1        JPM,BAC,GS
dtype: object

In [44]:
tickets.str.split(',')

0    [GOOG, APPL, AMZN]
1        [JPM, BAC, GS]
dtype: object

In [45]:
tickets.str.split(',').str[0]

0    GOOG
1     JPM
dtype: object

In [46]:
tickets.str.split(',',expand=True)

      0     1     2
0  GOOG  APPL  AMZN
1   JPM   BAC    GS

In [47]:
messy_names = pd.Series(["andrew  ","bo;bo","  claire  "])
messy_names

0      andrew
1         bo;bo
2      claire
dtype: object

In [48]:
messy_names.str.replace(";","")

0      andrew
1          bobo
2      claire
dtype: object

In [49]:
messy_names.str.strip()

0    andrew
1     bo;bo
2    claire
dtype: object

In [50]:
messy_names.str.replace(";","").str.strip()

0    andrew
1      bobo
2    claire
dtype: object

In [51]:
messy_names.str.replace(";","").str.strip().str.capitalize()

0    Andrew
1      Bobo
2    Claire
dtype: object

In [52]:
from datetime import datetime

In [53]:
my_year = 2017
my_month = 1
my_day = 2
my_hour = 13
my_minute = 30
my_second = 15

In [54]:
my_date = datetime(my_year,my_month,my_day)
my_date

datetime.datetime(2017, 1, 2, 0, 0)

In [55]:
my_date.day

2

In [56]:
my_date.hour

0

In [57]:
myser = pd.Series(['Nov 3, 2000', '2000-01-01', None])
myser

0    Nov 3, 2000
1     2000-01-01
2           None
dtype: object

In [58]:
myser[0]

'Nov 3, 2000'

In [59]:
pd.to_datetime(myser)[0]

ValueError: time data "2000-01-01" doesn't match format "%b %d, %Y", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
obvi_euro_date = '31-12-2000'

In [60]:
pd.to_datetime(obvi_euro_date)

C:\Users\administrator\AppData\Local\Temp\ipykernel_6420\163700324.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  pd.to_datetime(obvi_euro_date)

Timestamp('2000-12-31 00:00:00')

In [71]:
sales = pd.read_csv('RetailSales_BeerWineLiquor.csv',parse_dates=[0])
sales

          DATE  MRTSSM4453USN
0   1992-01-01           1509
1   1992-02-01           1541
2   1992-03-01           1597
3   1992-04-01           1675
4   1992-05-01           1822
..         ...            ...
335 2019-12-01           6630
336 2020-01-01           4388
337 2020-02-01           4533
338 2020-03-01           5562
339 2020-04-01           5207

[340 rows x 2 columns]

In [72]:
type(sales.iloc[0]['DATE'])

pandas._libs.tslibs.timestamps.Timestamp

In [73]:
sales.index

RangeIndex(start=0, stop=340, step=1)

In [74]:
sales = sales.set_index("DATE")

In [75]:
sales

            MRTSSM4453USN
DATE
1992-01-01           1509
1992-02-01           1541
1992-03-01           1597
1992-04-01           1675
1992-05-01           1822
...                   ...
2019-12-01           6630
2020-01-01           4388
2020-02-01           4533
2020-03-01           5562
2020-04-01           5207

[340 rows x 1 columns]

In [76]:
sales.resample(rule='A').mean()

C:\Users\administrator\AppData\Local\Temp\ipykernel_6420\229365907.py:1: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  sales.resample(rule='A').mean()

            MRTSSM4453USN
DATE
1992-12-31    1807.250000
1993-12-31    1794.833333
1994-12-31    1841.750000
1995-12-31    1833.916667
1996-12-31    1929.750000
1997-12-31    2006.750000
1998-12-31    2115.166667
1999-12-31    2206.333333
2000-12-31    2375.583333
2001-12-31    2468.416667
2002-12-31    2491.166667
2003-12-31    2539.083333
2004-12-31    2682.416667
2005-12-31    2797.250000
2006-12-31    3001.333333
2007-12-31    3177.333333
2008-12-31    3292.000000
2009-12-31    3353.750000
2010-12-31    3450.083333
2011-12-31    3532.666667
2012-12-31    3697.083333
2013-12-31    3839.666667
2014-12-31    4023.833333
2015-12-31    4212.500000
2016-12-31    4434.416667
2017-12-31    4602.666667
2018-12-31    4830.666667
2019-12-31    4972.750000
2020-12-31    4922.500000

In [77]:
sales = sales.reset_index()

In [78]:
sales

          DATE  MRTSSM4453USN
0   1992-01-01           1509
1   1992-02-01           1541
2   1992-03-01           1597
3   1992-04-01           1675
4   1992-05-01           1822
..         ...            ...
335 2019-12-01           6630
336 2020-01-01           4388
337 2020-02-01           4533
338 2020-03-01           5562
339 2020-04-01           5207

[340 rows x 2 columns]

In [79]:
help(sales['DATE'].dt)

Help on DatetimeProperties in module pandas.core.indexes.accessors object:

class DatetimeProperties(Properties)
 |  DatetimeProperties(data: 'Series', orig) -> 'None'
 |
 |  Accessor object for datetimelike properties of the Series values.
 |
 |  Examples
 |  --------
 |  >>> seconds_series = pd.Series(pd.date_range("2000-01-01", periods=3, freq="s"))
 |  >>> seconds_series
 |  0   2000-01-01 00:00:00
 |  1   2000-01-01 00:00:01
 |  2   2000-01-01 00:00:02
 |  dtype: datetime64[ns]
 |  >>> seconds_series.dt.second
 |  0    0
 |  1    1
 |  2    2
 |  dtype: int32
 |
 |  >>> hours_series = pd.Series(pd.date_range("2000-01-01", periods=3, freq="h"))
 |  >>> hours_series
 |  0   2000-01-01 00:00:00
 |  1   2000-01-01 01:00:00
 |  2   2000-01-01 02:00:00
 |  dtype: datetime64[ns]
 |  >>> hours_series.dt.hour
 |  0    0
 |  1    1
 |  2    2
 |  dtype: int32
 |
 |  >>> quarters_series = pd.Series(pd.date_range("2000-01-01", periods=3, freq="QE"))
 |  >>> quarters_series
 |  0   2000-03-31
 |  1   2000-06-30
 |  2   2000-09-30
 |  dtype: datetime64[ns]
 |  >>> quarters_series.dt.quarter
 |  0    1
 |  1    2
 |  2    3
 |  dtype: int32
 |
 |  Returns a Series indexed like the original Series.
 |  Raises TypeError if the Series does not contain datetimelike values.
 |
 |  Method resolution order:
 |      DatetimeProperties
 |      Properties
 |      pandas.core.accessor.PandasDelegate
 |      pandas.core.base.PandasObject
 |      pandas.core.accessor.DirNamesMixin
 |      pandas.core.base.NoNewAttributesMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  as_unit(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |
 |  ceil(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |      Perform ceil operation on the data to the specified `freq`.
 |
 |      Parameters
 |      ----------
 |      freq : str or Offset
 |          The frequency level to ceil the index to. Must be a fixed
 |          frequency like 'S' (second) not 'ME' (month end). See
 |          :ref:`frequency aliases <timeseries.offset_aliases>` for
 |          a list of possible `freq` values.
 |      ambiguous : 'infer', bool-ndarray, 'NaT', default 'raise'
 |          Only relevant for DatetimeIndex:
 |
 |          - 'infer' will attempt to infer fall dst-transition hours based on
 |            order
 |          - bool-ndarray where True signifies a DST time, False designates
 |            a non-DST time (note that this flag is only applicable for
 |            ambiguous times)
 |          - 'NaT' will return NaT where there are ambiguous times
 |          - 'raise' will raise an AmbiguousTimeError if there are ambiguous
 |            times.
 |
 |      nonexistent : 'shift_forward', 'shift_backward', 'NaT', timedelta, default 'raise'
 |          A nonexistent time does not exist in a particular timezone
 |          where clocks moved forward due to DST.
 |
 |          - 'shift_forward' will shift the nonexistent time forward to the
 |            closest existing time
 |          - 'shift_backward' will shift the nonexistent time backward to the
 |            closest existing time
 |          - 'NaT' will return NaT where there are nonexistent times
 |          - timedelta objects will shift nonexistent times by the timedelta
 |          - 'raise' will raise an NonExistentTimeError if there are
 |            nonexistent times.
 |
 |      Returns
 |      -------
 |      DatetimeIndex, TimedeltaIndex, or Series
 |          Index of the same type for a DatetimeIndex or TimedeltaIndex,
 |          or a Series with the same index for a Series.
 |
 |      Raises
 |      ------
 |      ValueError if the `freq` cannot be converted.
 |
 |      Notes
 |      -----
 |      If the timestamps have a timezone, ceiling will take place relative to the
 |      local ("wall") time and re-localized to the same timezone. When ceiling
 |      near daylight savings time, use ``nonexistent`` and ``ambiguous`` to
 |      control the re-localization behavior.
 |
 |      Examples
 |      --------
 |      **DatetimeIndex**
 |
 |      >>> rng = pd.date_range('1/1/2018 11:59:00', periods=3, freq='min')
 |      >>> rng
 |      DatetimeIndex(['2018-01-01 11:59:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 12:01:00'],
 |                    dtype='datetime64[ns]', freq='min')
 |      >>> rng.ceil('h')
 |      DatetimeIndex(['2018-01-01 12:00:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 13:00:00'],
 |                    dtype='datetime64[ns]', freq=None)
 |
 |      **Series**
 |
 |      >>> pd.Series(rng).dt.ceil("h")
 |      0   2018-01-01 12:00:00
 |      1   2018-01-01 12:00:00
 |      2   2018-01-01 13:00:00
 |      dtype: datetime64[ns]
 |
 |      When rounding near a daylight savings time transition, use ``ambiguous`` or
 |      ``nonexistent`` to control how the timestamp should be re-localized.
 |
 |      >>> rng_tz = pd.DatetimeIndex(["2021-10-31 01:30:00"], tz="Europe/Amsterdam")
 |
 |      >>> rng_tz.ceil("h", ambiguous=False)
 |      DatetimeIndex(['2021-10-31 02:00:00+01:00'],
 |                    dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
 |
 |      >>> rng_tz.ceil("h", ambiguous=True)
 |      DatetimeIndex(['2021-10-31 02:00:00+02:00'],
 |                    dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
 |
 |  day_name(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |      Return the day names with specified locale.
 |
 |      Parameters
 |      ----------
 |      locale : str, optional
 |          Locale determining the language in which to return the day name.
 |          Default is English locale (``'en_US.utf8'``). Use the command
 |          ``locale -a`` on your terminal on Unix systems to find your locale
 |          language code.
 |
 |      Returns
 |      -------
 |      Series or Index
 |          Series or Index of day names.
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series(pd.date_range(start='2018-01-01', freq='D', periods=3))
 |      >>> s
 |      0   2018-01-01
 |      1   2018-01-02
 |      2   2018-01-03
 |      dtype: datetime64[ns]
 |      >>> s.dt.day_name()
 |      0       Monday
 |      1      Tuesday
 |      2    Wednesday
 |      dtype: object
 |
 |      >>> idx = pd.date_range(start='2018-01-01', freq='D', periods=3)
 |      >>> idx
 |      DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03'],
 |                    dtype='datetime64[ns]', freq='D')
 |      >>> idx.day_name()
 |      Index(['Monday', 'Tuesday', 'Wednesday'], dtype='object')
 |
 |      Using the ``locale`` parameter you can set a different locale language,
 |      for example: ``idx.day_name(locale='pt_BR.utf8')`` will return day
 |      names in Brazilian Portuguese language.
 |
 |      >>> idx = pd.date_range(start='2018-01-01', freq='D', periods=3)
 |      >>> idx
 |      DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03'],
 |                    dtype='datetime64[ns]', freq='D')
 |      >>> idx.day_name(locale='pt_BR.utf8') # doctest: +SKIP
 |      Index(['Segunda', 'Terça', 'Quarta'], dtype='object')
 |
 |  floor(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |      Perform floor operation on the data to the specified `freq`.
 |
 |      Parameters
 |      ----------
 |      freq : str or Offset
 |          The frequency level to floor the index to. Must be a fixed
 |          frequency like 'S' (second) not 'ME' (month end). See
 |          :ref:`frequency aliases <timeseries.offset_aliases>` for
 |          a list of possible `freq` values.
 |      ambiguous : 'infer', bool-ndarray, 'NaT', default 'raise'
 |          Only relevant for DatetimeIndex:
 |
 |          - 'infer' will attempt to infer fall dst-transition hours based on
 |            order
 |          - bool-ndarray where True signifies a DST time, False designates
 |            a non-DST time (note that this flag is only applicable for
 |            ambiguous times)
 |          - 'NaT' will return NaT where there are ambiguous times
 |          - 'raise' will raise an AmbiguousTimeError if there are ambiguous
 |            times.
 |
 |      nonexistent : 'shift_forward', 'shift_backward', 'NaT', timedelta, default 'raise'
 |          A nonexistent time does not exist in a particular timezone
 |          where clocks moved forward due to DST.
 |
 |          - 'shift_forward' will shift the nonexistent time forward to the
 |            closest existing time
 |          - 'shift_backward' will shift the nonexistent time backward to the
 |            closest existing time
 |          - 'NaT' will return NaT where there are nonexistent times
 |          - timedelta objects will shift nonexistent times by the timedelta
 |          - 'raise' will raise an NonExistentTimeError if there are
 |            nonexistent times.
 |
 |      Returns
 |      -------
 |      DatetimeIndex, TimedeltaIndex, or Series
 |          Index of the same type for a DatetimeIndex or TimedeltaIndex,
 |          or a Series with the same index for a Series.
 |
 |      Raises
 |      ------
 |      ValueError if the `freq` cannot be converted.
 |
 |      Notes
 |      -----
 |      If the timestamps have a timezone, flooring will take place relative to the
 |      local ("wall") time and re-localized to the same timezone. When flooring
 |      near daylight savings time, use ``nonexistent`` and ``ambiguous`` to
 |      control the re-localization behavior.
 |
 |      Examples
 |      --------
 |      **DatetimeIndex**
 |
 |      >>> rng = pd.date_range('1/1/2018 11:59:00', periods=3, freq='min')
 |      >>> rng
 |      DatetimeIndex(['2018-01-01 11:59:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 12:01:00'],
 |                    dtype='datetime64[ns]', freq='min')
 |      >>> rng.floor('h')
 |      DatetimeIndex(['2018-01-01 11:00:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 12:00:00'],
 |                    dtype='datetime64[ns]', freq=None)
 |
 |      **Series**
 |
 |      >>> pd.Series(rng).dt.floor("h")
 |      0   2018-01-01 11:00:00
 |      1   2018-01-01 12:00:00
 |      2   2018-01-01 12:00:00
 |      dtype: datetime64[ns]
 |
 |      When rounding near a daylight savings time transition, use ``ambiguous`` or
 |      ``nonexistent`` to control how the timestamp should be re-localized.
 |
 |      >>> rng_tz = pd.DatetimeIndex(["2021-10-31 03:30:00"], tz="Europe/Amsterdam")
 |
 |      >>> rng_tz.floor("2h", ambiguous=False)
 |      DatetimeIndex(['2021-10-31 02:00:00+01:00'],
 |                   dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
 |
 |      >>> rng_tz.floor("2h", ambiguous=True)
 |      DatetimeIndex(['2021-10-31 02:00:00+02:00'],
 |                    dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
 |
 |  isocalendar(self) -> 'DataFrame'
 |      Calculate year, week, and day according to the ISO 8601 standard.
 |
 |      Returns
 |      -------
 |      DataFrame
 |          With columns year, week and day.
 |
 |      See Also
 |      --------
 |      Timestamp.isocalendar : Function return a 3-tuple containing ISO year,
 |          week number, and weekday for the given Timestamp object.
 |      datetime.date.isocalendar : Return a named tuple object with
 |          three components: year, week and weekday.
 |
 |      Examples
 |      --------
 |      >>> ser = pd.to_datetime(pd.Series(["2010-01-01", pd.NaT]))
 |      >>> ser.dt.isocalendar()
 |         year  week  day
 |      0  2009    53     5
 |      1  <NA>  <NA>  <NA>
 |      >>> ser.dt.isocalendar().week
 |      0      53
 |      1    <NA>
 |      Name: week, dtype: UInt32
 |
 |  month_name(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |      Return the month names with specified locale.
 |
 |      Parameters
 |      ----------
 |      locale : str, optional
 |          Locale determining the language in which to return the month name.
 |          Default is English locale (``'en_US.utf8'``). Use the command
 |          ``locale -a`` on your terminal on Unix systems to find your locale
 |          language code.
 |
 |      Returns
 |      -------
 |      Series or Index
 |          Series or Index of month names.
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series(pd.date_range(start='2018-01', freq='ME', periods=3))
 |      >>> s
 |      0   2018-01-31
 |      1   2018-02-28
 |      2   2018-03-31
 |      dtype: datetime64[ns]
 |      >>> s.dt.month_name()
 |      0     January
 |      1    February
 |      2       March
 |      dtype: object
 |
 |      >>> idx = pd.date_range(start='2018-01', freq='ME', periods=3)
 |      >>> idx
 |      DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31'],
 |                    dtype='datetime64[ns]', freq='ME')
 |      >>> idx.month_name()
 |      Index(['January', 'February', 'March'], dtype='object')
 |
 |      Using the ``locale`` parameter you can set a different locale language,
 |      for example: ``idx.month_name(locale='pt_BR.utf8')`` will return month
 |      names in Brazilian Portuguese language.
 |
 |      >>> idx = pd.date_range(start='2018-01', freq='ME', periods=3)
 |      >>> idx
 |      DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31'],
 |                    dtype='datetime64[ns]', freq='ME')
 |      >>> idx.month_name(locale='pt_BR.utf8')  # doctest: +SKIP
 |      Index(['Janeiro', 'Fevereiro', 'Março'], dtype='object')
 |
 |  normalize(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |      Convert times to midnight.
 |
 |      The time component of the date-time is converted to midnight i.e.
 |      00:00:00. This is useful in cases, when the time does not matter.
 |      Length is unaltered. The timezones are unaffected.
 |
 |      This method is available on Series with datetime values under
 |      the ``.dt`` accessor, and directly on Datetime Array/Index.
 |
 |      Returns
 |      -------
 |      DatetimeArray, DatetimeIndex or Series
 |          The same type as the original data. Series will have the same
 |          name and index. DatetimeIndex will have the same name.
 |
 |      See Also
 |      --------
 |      floor : Floor the datetimes to the specified freq.
 |      ceil : Ceil the datetimes to the specified freq.
 |      round : Round the datetimes to the specified freq.
 |
 |      Examples
 |      --------
 |      >>> idx = pd.date_range(start='2014-08-01 10:00', freq='h',
 |      ...                     periods=3, tz='Asia/Calcutta')
 |      >>> idx
 |      DatetimeIndex(['2014-08-01 10:00:00+05:30',
 |                     '2014-08-01 11:00:00+05:30',
 |                     '2014-08-01 12:00:00+05:30'],
 |                      dtype='datetime64[ns, Asia/Calcutta]', freq='h')
 |      >>> idx.normalize()
 |      DatetimeIndex(['2014-08-01 00:00:00+05:30',
 |                     '2014-08-01 00:00:00+05:30',
 |                     '2014-08-01 00:00:00+05:30'],
 |                     dtype='datetime64[ns, Asia/Calcutta]', freq=None)
 |
 |  round(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |      Perform round operation on the data to the specified `freq`.
 |
 |      Parameters
 |      ----------
 |      freq : str or Offset
 |          The frequency level to round the index to. Must be a fixed
 |          frequency like 'S' (second) not 'ME' (month end). See
 |          :ref:`frequency aliases <timeseries.offset_aliases>` for
 |          a list of possible `freq` values.
 |      ambiguous : 'infer', bool-ndarray, 'NaT', default 'raise'
 |          Only relevant for DatetimeIndex:
 |
 |          - 'infer' will attempt to infer fall dst-transition hours based on
 |            order
 |          - bool-ndarray where True signifies a DST time, False designates
 |            a non-DST time (note that this flag is only applicable for
 |            ambiguous times)
 |          - 'NaT' will return NaT where there are ambiguous times
 |          - 'raise' will raise an AmbiguousTimeError if there are ambiguous
 |            times.
 |
 |      nonexistent : 'shift_forward', 'shift_backward', 'NaT', timedelta, default 'raise'
 |          A nonexistent time does not exist in a particular timezone
 |          where clocks moved forward due to DST.
 |
 |          - 'shift_forward' will shift the nonexistent time forward to the
 |            closest existing time
 |          - 'shift_backward' will shift the nonexistent time backward to the
 |            closest existing time
 |          - 'NaT' will return NaT where there are nonexistent times
 |          - timedelta objects will shift nonexistent times by the timedelta
 |          - 'raise' will raise an NonExistentTimeError if there are
 |            nonexistent times.
 |
 |      Returns
 |      -------
 |      DatetimeIndex, TimedeltaIndex, or Series
 |          Index of the same type for a DatetimeIndex or TimedeltaIndex,
 |          or a Series with the same index for a Series.
 |
 |      Raises
 |      ------
 |      ValueError if the `freq` cannot be converted.
 |
 |      Notes
 |      -----
 |      If the timestamps have a timezone, rounding will take place relative to the
 |      local ("wall") time and re-localized to the same timezone. When rounding
 |      near daylight savings time, use ``nonexistent`` and ``ambiguous`` to
 |      control the re-localization behavior.
 |
 |      Examples
 |      --------
 |      **DatetimeIndex**
 |
 |      >>> rng = pd.date_range('1/1/2018 11:59:00', periods=3, freq='min')
 |      >>> rng
 |      DatetimeIndex(['2018-01-01 11:59:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 12:01:00'],
 |                    dtype='datetime64[ns]', freq='min')
 |      >>> rng.round('h')
 |      DatetimeIndex(['2018-01-01 12:00:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 12:00:00'],
 |                    dtype='datetime64[ns]', freq=None)
 |
 |      **Series**
 |
 |      >>> pd.Series(rng).dt.round("h")
 |      0   2018-01-01 12:00:00
 |      1   2018-01-01 12:00:00
 |      2   2018-01-01 12:00:00
 |      dtype: datetime64[ns]
 |
 |      When rounding near a daylight savings time transition, use ``ambiguous`` or
 |      ``nonexistent`` to control how the timestamp should be re-localized.
 |
 |      >>> rng_tz = pd.DatetimeIndex(["2021-10-31 03:30:00"], tz="Europe/Amsterdam")
 |
 |      >>> rng_tz.floor("2h", ambiguous=False)
 |      DatetimeIndex(['2021-10-31 02:00:00+01:00'],
 |                    dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
 |
 |      >>> rng_tz.floor("2h", ambiguous=True)
 |      DatetimeIndex(['2021-10-31 02:00:00+02:00'],
 |                    dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
 |
 |  strftime(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |      Convert to Index using specified date_format.
 |
 |      Return an Index of formatted strings specified by date_format, which
 |      supports the same string format as the python standard library. Details
 |      of the string format can be found in `python string format
 |      doc <https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior>`__.
 |
 |      Formats supported by the C `strftime` API but not by the python string format
 |      doc (such as `"%R"`, `"%r"`) are not officially supported and should be
 |      preferably replaced with their supported equivalents (such as `"%H:%M"`,
 |      `"%I:%M:%S %p"`).
 |

In [80]:
pwd

'C:\\Users\\administrator\\PycharmProjects\\AI'

In [88]:
df = pd.read_csv('example.csv',index_col=0)

In [89]:
df

     b   c   d
a
0    1   2   3
4    5   6   7
8    9  10  11
12  13  14  15

In [91]:
df.to_csv('new_file.csv',index=False)

In [96]:
tables = pd.read_html('https://en.wikipedia.org/wiki/World_population')

HTTPError: HTTP Error 403: Forbidden

In [98]:
df = pd.read_csv('Sales_Funnel_CRM.csv')
df

,Account Number,Company,Contact,Account Manager,Product,Licenses,Sale Price,Status
0,2123398,Google,Larry Pager,Edward Thorp,Analytics,150,2100000,Presented
1,2123398,Google,Larry Pager,Edward Thorp,Prediction,150,700000,Presented
2,2123398,Google,Larry Pager,Edward Thorp,Tracking,300,350000,Under Review
3,2192650,BOBO,Larry Pager,Edward Thorp,Analytics,150,2450000,Lost
4,420496,IKEA,Elon Tusk,Edward Thorp,Analytics,300,4550000,Won
5,636685,Tesla Inc.,Elon Tusk,Edward Thorp,Analytics,300,2800000,Under Review
6,636685,Tesla Inc.,Elon Tusk,Edward Thorp,Prediction,150,700000,Presented
7,1216870,Microsoft,Will Grates,Edward Thorp,Tracking,300,350000,Under Review
8,2200450,Walmart,Will Grates,Edward Thorp,Analytics,150,2450000,Lost
9,405886,Apple,Cindy Phoner,Claude Shannon,Analytics,300,4550000,Won
10,470248,Exxon Mobile,Cindy Phoner,Claude Shannon,Analytics,150,2100000,Presented
11,698032,ATT,Cindy Phoner,Claude Shannon,Tracking,150,350000,Under Review
12,698032,ATT,Cindy Phoner,Claude Shannon,Prediction,150,700000,Presented
13,902797,CVS Health,Emma Gordian,Claude Shannon,Tracking,450,490000,Won
14,2046943,Salesforce,Emma Gordian,Claude Shannon,Analytics,750,7000000,Won
15,2169499,Cisco,Emma Gordian,Claude Shannon,Analytics,300,4550000,Lost
16,2169499,Cisco,Emma Gordian,Claude Shannon,GPS Positioning,300,350000,Presented

In [99]:
licenses = df[['Company','Product','Licenses']]
licenses

         Company          Product  Licenses
0         Google        Analytics       150
1         Google       Prediction       150
2         Google         Tracking       300
3           BOBO        Analytics       150
4           IKEA        Analytics       300
5     Tesla Inc.        Analytics       300
6     Tesla Inc.       Prediction       150
7      Microsoft         Tracking       300
8        Walmart        Analytics       150
9          Apple        Analytics       300
10  Exxon Mobile        Analytics       150
11           ATT         Tracking       150
12           ATT       Prediction       150
13    CVS Health         Tracking       450
14    Salesforce        Analytics       750
15         Cisco        Analytics       300
16         Cisco  GPS Positioning       300

In [100]:
pd.pivot(data=licenses,index='Company',columns='Product',values='Licenses')

Product       Analytics  GPS Positioning  Prediction  Tracking
Company
 Google           150.0              NaN       150.0     300.0
ATT                 NaN              NaN       150.0     150.0
Apple             300.0              NaN         NaN       NaN
BOBO              150.0              NaN         NaN       NaN
CVS Health          NaN              NaN         NaN     450.0
Cisco             300.0            300.0         NaN       NaN
Exxon Mobile      150.0              NaN         NaN       NaN
IKEA              300.0              NaN         NaN       NaN
Microsoft           NaN              NaN         NaN     300.0
Salesforce        750.0              NaN         NaN       NaN
Tesla Inc.        300.0              NaN       150.0       NaN
Walmart           150.0              NaN         NaN       NaN

In [101]:
pd.pivot_table(df,index="Company",aggfunc='sum')

,Account Manager,Account Number,Contact,Licenses,Product,Sale Price,Status
Company,,,,,,,
Google,Edward ThorpEdward ThorpEdward Thorp,6370194,Larry PagerLarry PagerLarry Pager,600,AnalyticsPredictionTracking,3150000,PresentedPresentedUnder Review
ATT,Claude ShannonClaude Shannon,1396064,Cindy PhonerCindy Phoner,300,TrackingPrediction,1050000,Under ReviewPresented
Apple,Claude Shannon,405886,Cindy Phoner,300,Analytics,4550000,Won
BOBO,Edward Thorp,2192650,Larry Pager,150,Analytics,2450000,Lost
CVS Health,Claude Shannon,902797,Emma Gordian,450,Tracking,490000,Won
Cisco,Claude ShannonClaude Shannon,4338998,Emma GordianEmma Gordian,600,AnalyticsGPS Positioning,4900000,LostPresented
Exxon Mobile,Claude Shannon,470248,Cindy Phoner,150,Analytics,2100000,Presented
IKEA,Edward Thorp,420496,Elon Tusk,300,Analytics,4550000,Won
Microsoft,Edward Thorp,1216870,Will Grates,300,Tracking,350000,Under Review
Salesforce,Claude Shannon,2046943,Emma Gordian,750,Analytics,7000000,Won
Tesla Inc.,Edward ThorpEdward Thorp,1273370,Elon TuskElon Tusk,450,AnalyticsPrediction,3500000,Under ReviewPresented
Walmart,Edward Thorp,2200450,Will Grates,150,Analytics,2450000,Lost

In [102]:
pd.pivot_table(df,index="Company",aggfunc='sum')[['Licenses','Sale Price']]

              Licenses  Sale Price
Company
 Google            600     3150000
ATT                300     1050000
Apple              300     4550000
BOBO               150     2450000
CVS Health         450      490000
Cisco              600     4900000
Exxon Mobile       150     2100000
IKEA               300     4550000
Microsoft          300      350000
Salesforce         750     7000000
Tesla Inc.         450     3500000
Walmart            150     2450000

In [103]:
pd.pivot_table(df,index="Company",aggfunc='sum',values=['Licenses','Sale Price'])

              Licenses  Sale Price
Company
 Google            600     3150000
ATT                300     1050000
Apple              300     4550000
BOBO               150     2450000
CVS Health         450      490000
Cisco              600     4900000
Exxon Mobile       150     2100000
IKEA               300     4550000
Microsoft          300      350000
Salesforce         750     7000000
Tesla Inc.         450     3500000
Walmart            150     2450000

In [104]:
df.groupby('Company').sum()[['Licenses','Sale Price']]

              Licenses  Sale Price
Company
 Google            600     3150000
ATT                300     1050000
Apple              300     4550000
BOBO               150     2450000
CVS Health         450      490000
Cisco              600     4900000
Exxon Mobile       150     2100000
IKEA               300     4550000
Microsoft          300      350000
Salesforce         750     7000000
Tesla Inc.         450     3500000
Walmart            150     2450000

In [105]:
pd.pivot_table(df,index=["Account Manager","Contact"],values=['Sale Price'],aggfunc='sum')

                              Sale Price
Account Manager Contact
Claude Shannon  Cindy Phoner     7700000
                Emma Gordian    12390000
Edward Thorp    Elon Tusk        8050000
                Larry Pager      5600000
                Will Grates      2800000